# Generated by Django 6.1 on 2026-08-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
