# Generated by Django 6.1 on 2026-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_seed_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
